services:
  pysearch:
    build: .
    image: pysearch-image
    container_name: pysearch
    ports:
      - "3000:8000"
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      WORKERS: 2
      TIMEOUT: 120
