import os
from pathlib import Path
from dotenv import load_dotenv

env_path = Path("../.env")

load_dotenv(dotenv_path= env_path)

PINECONE_KEY = os.getenv("PINECONE_KEY")
PINECONE_ENVIRONMENT = os.getenv("PINECONE_ENVIRONMENT")
PINECONE_INDEX = os.getenv("PINECONE_INDEX")
PINECONE_NAMESPACE = os.getenv("PINECONE_NAMESPACE")
PINECONE_RESPONSE_COUNT = int(os.getenv("PINECONE_RESPONSE_COUNT"))
SEARCH_SERVICE_PORT = int(os.getenv("SEARCH_SERVICE_PORT"))
SEARCH_SERVICE_ROUTE = os.getenv("SEARCH_SERVICE_ROUTE")
SEARCH_SERVICE_CONCURRENCY = int(os.getenv("SEARCH_SERVICE_CONCURRENCY"))

MAX_CONCURRENT_TASKS = SEARCH_SERVICE_CONCURRENCY

